### ISSUE TITLE
feat :  채팅 페이지 구현

### ISSUE THREAD

**Issue by juliaha9709** [CSID-DGU/2022-1-CECD3-EverySon-2#18]
## Description

> 채팅 페이지 구현

## Todo

- [x] App Bar 구현
- [x] 채팅 입력창 구현
- [x] 챗버블 구현
- [x] Navigator (to Settings) 구현
- [ ] 채팅 서버 연동
